version: "3.8"

volumes:
  pgsql-data:

services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    container_name: pgsql-data
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgsql-data
        target: /var/lib/postgresql/data